### PR TITLE
Fix issue #6, add template intercepter, update to work with rest 2.0.0

### LINKED ISSUE #6: `per_page` option stopped working after version 0.0.2
It appears as though adding a per_page option  stopped working in version 1.0.0, so that queries will still return the default number of posts (10). This might affect adding other options/params to a query as well.

Using the following test with my project:

``` javascript
api.awards.get({ per_page: 20 })
  .then((result) => console.log(result.length))
```

Version 0.0.2 logs 16.
Version 1.0.0 logs 10.

### PR DESCRIPTION
**Pull request by michaelcd**
Ready for review.
- Updated rooftop-client to work with params again, with the update of rest to v2.0.0
- Updated failing params test to pass.
- Added second test for multiple params.
- Example template intercepter query format for reference:
  `{?per_page,order,orderby}`

Closes #6

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -42,15 +44,19 @@ const Rooftop = {
...
       name: opts.name,
       apiToken: opts.apiToken,
       contentType: (name) => {
         return {
           get: (opts) => {
-            return client(Object.assign({ path: name }, { params: opts }))
+            let pathTemplate = name
+            if (opts) {
+              for (let param in opts) { pathTemplate += `{?${param}}` }
+            }
```
Comment (jescalan) [inline lib/index.js]: [objectfn](https://github.com/jescalan/objectfn) could help to abbreviate this if you want!

Comment (michaelcd) [reply lib/index.js]: Good call. :smile: I'll throw that in.

Comment (michaelcd) [reply lib/index.js]: Actually `Object.keys` seemed to be the best way to handle this. See my most recent push.

File: lib/index.js [hunk 2]
```diff
@@ -42,15 +43,18 @@ const Rooftop = {
...
+      }).wrap(template, { params: {} })
 
     return new Proxy({
       name: opts.name,
       apiToken: opts.apiToken,
       contentType: (name) => {
         return {
           get: (opts) => {
-            return client(Object.assign({ path: name }, { params: opts }))
+            opts = opts || {}
```
Comment (jescalan) [inline lib/index.js]: you can do `get: (opts = {}) =>` instead

Comment (michaelcd) [reply lib/index.js]: True. Forgot about that in ES6. Will fix

**Comment by michaelcd** [comment]
@jescalan Any other thoughts on this PR?

**Comment by jescalan** [comment]
Looking good! Thanks for checking in 👍
